# -*- coding: utf-8 -*-
"""Interview Prep Analytics and Engineering - Test 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVPcfEmo4EK4Ob_DU2No-M82KBOf9zec

# **Interview Preparation**

QUESTION 1 >>>>

SQL: Identifying High-Impact Delays in Order
Fulfillment
A company needs a report identifying orders where the actual delivery time exceeded the expected delivery time.
The results should have the following columns: order_id / customer_id I delay_days / average_monthly_delay.
* order_id - Unique identifier for delayed order.
* customer_id - Customer who placed the order.
* delay_days - Number of days thelorder delivery was delayed from its actual delivery date.
* average_monthly_delay - Average delay for all orders in that month, rounded to two decimal places, including trailing zeros if necessary (e.g., 5.00).

Note:
* When calculating the average monthly delay, assign the delay (X days between actual and expected delivery date) to the month in which the order was placed.
* Only orders where the actual delivery time exceeded the expected delivery time by more than 5 times the rounded average delay (in days) for that delivery
month should be included in the result.

Schema: Orders (id, customer_id, order_date, expected_delivery_date, actual_delivery_date
"""

CREATE TABLE orders (
    id INT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    expected_delivery_date DATE,
    actual_delivery_date DATE
);

INSERT INTO orders (id, customer_id, order_date, expected_delivery_date, actual_delivery_date) VALUES
-- January orders
(1, 101, '2024-01-02', '2024-01-05', '2024-01-06'),  -- 1 day delay
(2, 102, '2024-01-05', '2024-01-08', '2024-01-10'),  -- 2 days delay
(3, 103, '2024-01-10', '2024-01-12', '2024-01-20'),  -- 8 days delay (high)
(4, 104, '2024-01-12', '2024-01-15', '2024-01-15'),  -- 0 delay
(5, 105, '2024-01-15', '2024-01-18', '2024-01-25'),  -- 7 days delay (high)

-- February orders
(6, 101, '2024-02-01', '2024-02-04', '2024-02-05'),  -- 1 day delay
(7, 102, '2024-02-03', '2024-02-06', '2024-02-08'),  -- 2 days delay
(8, 103, '2024-02-05', '2024-02-08', '2024-02-20'),  -- 12 days delay (very high)
(9, 104, '2024-02-10', '2024-02-13', '2024-02-13'),  -- 0 delay
(10, 105, '2024-02-15', '2024-02-18', '2024-02-19'), -- 1 day delay

-- March orders
(11, 101, '2024-03-01', '2024-03-05', '2024-03-07'), -- 2 days delay
(12, 102, '2024-03-03', '2024-03-06', '2024-03-15'), -- 9 days delay (high)
(13, 103, '2024-03-07', '2024-03-10', '2024-03-11'), -- 1 day delay
(14, 104, '2024-03-10', '2024-03-13', '2024-03-25'), -- 12 days delay (very high)
(15, 105, '2024-03-15', '2024-03-18', '2024-03-18'); -- 0 delay

WITH delayed_orders AS (
  SELECT

  id AS order_id,
  customer_id,
  expected_delivery_date,
  actual_delivery_date,
  DATEDIFF(actual_delivery_date,expected_delivery_date) as delivery_days, --For accounting for Note point 1
  DATE_FORMAT(order_date, '%Y-%M-01') AS order_month -- For accounting for Note point 2

  FROM orders
  ),

 monthly_avg AS (
    SELECT

    order_month,
    ROUND(AVG(delivery_days),2) AS average_monthly_delay

    FROM delayed_orders
    GROUP BY order_month

  )

  SELECT

    A.order_id,
    A.customer_id,
    A.delivery_days as delay_days,
    B.average_monthly_delay

  FROM delayed_orders A
  JOIN monthly_avg B
  	ON A.order_id = B.order_id

 WHERE A.delivery_days > 5 * B.average_monthly_delay

"""QUESTION 2 >>>>

Python Basic: Implement a custom exception class called NegativeValueError that inherits from ValueError, and a function validate_positive.

The function should:

✅ Return the input value if it is positive
❌ Raise NegativeValueError with message "Input value is negative" if the value is negative
📌 Example:
value = -4
validate_positive(-4)

❌ Output:

NegativeValueError: Input value is negative
"""

# Step 1: Create a custom exception by inheriting from ValueError
class NegativeValueError(ValueError):
    pass  # No extra logic needed, we just want a custom error type


# Step 2: Define the function to validate input
def validate_positive(value):

    # Check if the value is negative
    if value < 0:
        # Raise custom exception with a clear message
        raise NegativeValueError("Input value is negative")

    # If value is positive, return it as-is
    return value

# Example usage

try:
    result = validate_positive(-4)
except NegativeValueError as e:
    print(e)

"""QUESTION 3 >>>>

Statistics: A given population has been divided into 3 categories along with the number of samples as shown below. 10 samples are picked randomly using the stratified method.
What will be the distribution of each category in the sample?

Category A - 50
Category B - 40
Category C - 10
Total - 100

*Solution: Find proportion of each category*

Proportion = Category Size / Total Population

Category A: 0.5
Category B: 0.4
Category C: 0.1

Samples Selected would be as below:

A:B:C = 5:4:1

This would represent the population in their exact proportion.

QUESTION 4 >>>>

Implement a class called database_context_manager that acts as a context manager for database connections.
The context manager should:
* Create a database connection when entering the context by calling the _init_db method (already defined in the Database class)
* Close the connection when exiting the context by calling the _close_db method (also defined in the
* Database class)
Given a string username consisting of lowercase English letters, define and complete the database_context_manager class.
For a successful simulation:
* The input string username must be passed to _init_db0 as an argument.
•The connection string returned from _init_d must be passed to _close_db as an argument to close the connection.
Example
Given input username = "Sam", if the connection string
returned by _init_db is "abc":
* "Sam" must be passed as an argument to _init_dbl
* "abc" must be passed to _close_dbl
Function Description
Complete the class database_context_manager in the editor with the following parameters):
string username: the string to pass to _init_dbl


Constraints
* 1 ≤ / username 1 ≤ 105
* username consists of lowercase English letters.
"""

# Assume this Database class is already provided
class Database:

    def _init_db(self, username):
        # Simulates opening a DB connection
        print(f"Opening connection for {username}")
        return "connection_string_abc"  # Example connection string

    def _close_db(self, connection_string):
        # Simulates closing a DB connection
        print(f"Closing connection: {connection_string}")


# Your task: implement this class
class database_context_manager:

    # Constructor → stores username and creates Database object
    def __init__(self, username):
        self.username = username              # Store input username
        self.db = Database()                  # Create Database instance
        self.connection = None                # Placeholder for connection string

    # Called when entering the 'with' block
    def __enter__(self):
        # Call _init_db and store the connection string
        self.connection = self.db._init_db(self.username)

        # Return connection so it can be used inside 'with'
        return self.connection

    # Called when exiting the 'with' block
    def __exit__(self, exc_type, exc_value, traceback):
        # Use stored connection string to close DB
        if self.connection:
            self.db._close_db(self.connection)

        # Optional: handle exceptions (return False → propagate error)
        return False

with database_context_manager("sam") as conn:
    print(f"Using connection: {conn}")

"""**Code Flow Explanation**

The database_context_manager class is designed to safely manage a database connection using Python’s context manager protocol (the with statement).

When an object of this class is created, the __init__ method is automatically executed. This method takes a username as input and stores it inside the object for later use. It also creates an instance of the Database class, which provides methods to initialize and close a database connection. Additionally, a placeholder variable is initialized to store the connection string once it is created.

When the with block begins execution, Python automatically calls the __enter__ method of the class. Inside this method, the database connection is established by calling the _init_db method of the Database class, passing the stored username as an argument. The connection string returned from this method is stored inside the object so it can be reused later. The __enter__ method then returns this connection string, allowing it to be used inside the with block (for example, assigned to a variable like conn).

The code inside the with block is then executed using the active database connection. This is where any operations involving the database would typically take place.

Once the with block finishes execution—whether it completes successfully or an error occurs—Python automatically calls the __exit__ method. This ensures that cleanup logic is always executed. Inside this method, the previously stored connection string is used to close the database connection by calling the _close_db method of the Database class.

By structuring the code this way, the class guarantees that the database connection is always properly closed, even if an unexpected error occurs during execution. This makes the code safer, cleaner, and less prone to resource leaks.

🔁 Execution Flow Summary
Object is created → __init__ runs
with block starts → __enter__ runs (opens connection)
Code inside with executes
with block ends → __exit__ runs (closes connection)

QUESTION 5 >>>>

A user is not signed in Tableau Server or Tableau Online but the given string is "All Users" in ISMEMBEROF function. What is the expected result ?

TRUE
1
0
NULL

*Solution*

The correct answer is: **❌ NULL**

---

## 🧠 Explanation

When you use:

```sql
ISMEMBEROF("All Users")
```

👉 Tableau checks whether the **currently logged-in user belongs to that group**.

---

## 🚨 Key Condition in the Question

> **User is NOT signed in** to Tableau Server / Tableau Online

This is the critical part.

---

## 🔍 What happens internally?

* Tableau **does not know who the user is**
* No identity → no group membership can be evaluated
* So the function **cannot return TRUE or FALSE**

---

## ✅ Final Behavior

👉 `ISMEMBEROF("All Users")` returns:

**➡️ NULL**

---

## ❓ Why not TRUE?

Even though *"All Users"* sounds like everyone:

* Tableau still requires a **valid authenticated user session**
* Without login → user context is missing

QUESTION 6 >>>>

Tableau: Which statement would remove duplicate from the below tabular data ?

Student ID | Marks
10010 | 90
10011 | 98
10012 | 95
10012 | 95
10013 | 85
10014 | 89
10013 | 85
10015 | 78
10014 | 89

Options:

{Fixed [Student ID): MIN([Marks])}

{Fixed [Student ID): MAX(IMarks])}

{lnclude [Student ID]: MIN([Marks])}

{lnclude [Student ID]: MAX([Marks])}

*Solution*

This is a **classic Tableau LOD + duplicates question**—and the trick is understanding how **FIXED vs INCLUDE behaves with duplicates**.

---

# 🧠 First: Understand the Data

You have duplicate rows like:

| Student ID | Marks |             |
| ---------- | ----- | ----------- |
| 10012      | 95    |             |
| 10012      | 95    | ❗ duplicate |
| 10013      | 85    |             |
| 10013      | 85    | ❗ duplicate |

👉 Goal: **Remove duplicates → keep 1 row per Student ID**

---

# 🔍 Evaluate Each Option

## ✅ Option 1:

```sql id="tq4aq2"
{ FIXED [Student ID] : MIN([Marks]) }
```

### ✔ What it does:

* Groups data at **Student ID level**
* Returns one value per Student ID
* Collapses duplicates

👉 For duplicates:

* 10012 → MIN(95,95) = 95
* Only one result per Student ID

✅ **Duplicates effectively removed**

---

## ✅ Option 2:

```sql id="gl4rkq"
{ FIXED [Student ID] : MAX([Marks]) }
```

👉 Same logic:

* One value per Student ID
* Removes duplicates

✅ **Also correct**

---

## ❌ Option 3:

```sql id="wz4lj0"
{ INCLUDE [Student ID] : MIN([Marks]) }
```

### ❗ Problem:

* INCLUDE depends on **view level of detail**
* Does NOT guarantee deduplication
* If duplicates exist in underlying data → they can still appear

❌ **Not reliable for removing duplicates**

---

## ❌ Option 4:

```sql id="s45fxq"
{ INCLUDE [Student ID] : MAX([Marks]) }
```

👉 Same issue as above

❌ **Not correct**

---

# ✅ Final Answer

👉 Correct statements are:

✔ `{ FIXED [Student ID] : MIN([Marks]) }`
✔ `{ FIXED [Student ID] : MAX([Marks]) }`

---

# 🎯 Key Concept (Very Important)

| LOD Type | Behavior                                |
| -------- | --------------------------------------- |
| FIXED    | Ignores view → good for deduplication ✅ |
| INCLUDE  | Depends on view → not reliable ❌        |

QUESTION 7 >>>>

Which function in tableau returns ISO-based week from a date column ? What's ISO ?

Options: ISOWEEKDAY | ISOWEEK | ISOWEEKNAME | WEEK

*Solution*

## ✅ Correct Answer: **ISOWEEK**

---

# 🧠 What does `ISOWEEK()` do?

👉 `ISOWEEK()` returns the **ISO 8601 week number** for a given date.

### Example:

```sql
ISOWEEK([Order Date])
```

👉 Output:

* Week numbers from **1 to 52/53**
* Based on **ISO standard (not regular calendar week)**

---

# ❓ What is ISO?

👉 **ISO = International Organization for Standardization**

👉 ISO 8601 defines a **standard way to represent dates & weeks globally**

---

# 📅 ISO Week Rules (VERY IMPORTANT)

1. **Week starts on Monday** (not Sunday ❗)
2. **Week 1 = the week that contains the first Thursday of the year**
3. Ensures **consistent week numbering across countries**

---

# 🔍 Example to Understand

| Date        | WEEK() | ISOWEEK() |
| ----------- | ------ | --------- |
| Jan 1, 2022 | 1      | 52 ❗      |
| Jan 3, 2022 | 2      | 1         |

👉 Why?

* Jan 1, 2022 falls in the **last ISO week of 2021**

---

# ❌ Why other options are wrong?

* `ISOWEEKDAY` → ❌ Not a valid Tableau function
* `ISOWEEKNAME` → ❌ Not a valid Tableau function
* `WEEK` → ❌ Uses standard (non-ISO) week logic

---
"""