# -*- coding: utf-8 -*-
"""SPX vs GOLD Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7zE_OtSjI9pd4mgRYMu8wI1pkgcMPl6
"""

"""
Gold Price Prediction Using Linear Regression
---------------------------------------------

Objective:
Predict Gold Prices using S&P 500 values based on 30 days of data.

Pipeline:
Data Creation >> EDA >> Handle Missing Values >> Train/Test Split >> Linear Regression Model >> Model Evaluation (MAE, MSE, R²) >> Linearity Validation >> Visualization >> Model Interpretation
"""

# ===============================
# 1. Import Libraries
# ===============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ===============================
# 2. Create 30 Days Sample Dataset
# ===============================

# Simulated relationship:

data = {
    "Day": range(1,31),

    "SP500":[5200,5215,5220,5190,5185,5230,5240,5250,5260,5270,
             5265,5255,5245,5235,5225,5210,5205,5195,5180,5175,
             5160,5155,5145,5135,5125,5115,5105,5095,5085,5075],

    "Gold":[2320,2315,2310,2330,2335,2305,2300,2295,2290,2285,
            np.nan,2292,2298,2305,2310,2315,np.nan,2325,2330,2335,
            2345,2350,2355,2360,2365,2370,2375,2380,np.nan,2390]
}

df = pd.DataFrame(data)

print("\nInitial Dataset")
print(df.head())

# ===============================
# 3. Exploratory Data Analysis
# ===============================

print("\nDataset Info")
print(df.info())

print("\nSummary Statistics")
print(df.describe())

print("\nMissing Values")
print(df.isnull().sum())

# ===============================
# 4. Handle Missing Values
# ===============================

# Missing gold prices may occur due to API failures or market holidays
# We use linear interpolation to estimate the missing values

df["Gold"] = df["Gold"].interpolate()

print("\nMissing Values After Interpolation")
print(df.isnull().sum())

# ===============================
# 5. Visual Exploration
# ===============================

plt.figure()
plt.scatter(df["SP500"], df["Gold"])
plt.xlabel("S&P 500")
plt.ylabel("Gold Price")
plt.title("Gold vs S&P500 Relationship")
plt.show()

# ===============================
# 6. Prepare Data for Model
# ===============================

X = df[["SP500"]]
y = df["Gold"]

# ===============================
# 7. Train Test Split
# ===============================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("\nTraining Samples:", len(X_train))
print("Testing Samples:", len(X_test))

# ===============================
# 8. Train Linear Regression Model
# ===============================

model = LinearRegression()
model.fit(X_train, y_train)

print("\nModel Parameters")
print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)

# ===============================
# 9. Predictions
# ===============================

y_pred = model.predict(X_test)

# ===============================
# 10. Model Evaluation
# ===============================

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nModel Performance")
print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

# ===============================
# 11. Validate Linearity Assumption
# ===============================

residuals = y_test - y_pred

plt.figure()
plt.scatter(y_pred, residuals)
plt.axhline(0)
plt.xlabel("Predicted Gold Price")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

# ===============================
# 12. Plot Regression Line
# ===============================

plt.figure()
plt.scatter(X, y)
plt.plot(X, model.predict(X))
plt.xlabel("S&P 500")
plt.ylabel("Gold Price")
plt.title("Linear Regression Fit")
plt.show()

# ===============================
# 13. Model Assumptions
# ===============================

print("""

Linear Regression Assumptions:

1. Linearity
Relationship between predictor and target should be linear.

2. No Economic News
Not factoring in the impact of Forex News

3. Sample random dataset
This is a sample dataset manually generated for practice

""")


# ===============================
# 14. Limitations
# ===============================

print("""

Limitations of This Model:

1. Gold price depends on multiple variables such as:
   - USD Index
   - Interest rates
   - Inflation
   - Oil prices
   - Geopolitical risk

2. Small dataset (30 days) limits model reliability.

3. Financial markets often exhibit nonlinear behavior.

""")

print("\nScript execution complete.")